version: "3.9"
name: node-app
services:
  node:
    container_name: node-lumia
    restart: always
    build: .
    ports:
      - 3000:3000
  mongo:
    container_name: mongo-lumia
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/${name:?err}/docker/volumes/mongodb:/data/db
volumes:
  mongodb: